Home work lesson 13
VladHedz/first-project pull request #9
Opened 2024-02-01 19:17 UTC by vlad-hedz-quarks-tech

* Selenoid запустив і прогнав один раз, більше не буду, бо ноуту на стільки погано стає, що не можу передати

2024-02-05 14:48 UTC, auris1g3 requested changes

2024-02-05 14:48 UTC, auris1g3 commented on src/main/java/pages/SwagLabs/CartPage.java
> +        }
Домашка зроблена дуже гарно, але є деякі моменти, тому трішки подушню))
Краще вартість прокинути параметрами,як ми логін і пароль вводимо. Тоді навіть в тесті буде гарно видно, які самі товари ми поклали в кошик

2024-02-05 14:48 UTC, auris1g3 commented on src/main/java/pages/SwagLabs/CartPage.java
> +    private static final SelenideElement CHECKOUT_BUTTON = $("[data-test='checkout']");
`private static final`  ось тут дуже гарно записати в статік, бо селектори не будуть змінюватися

2024-02-05 14:48 UTC, auris1g3 commented on src/main/java/pages/SwagLabs/InventoryPage.java
> +                INVENTORY_ITEMS.get(i).$(ADD_TO_CART_BUTTON_LOCATOR).click();
Так само, як вище, краще прокинути вартість параметрами. Можна до речі прокидати вараргсами, але це вже потім з досвідом. Простіше зробити два параметри.

2024-02-05 14:48 UTC, auris1g3 commented on src/main/java/pages/SwagLabs/LoginPage.java
> +
Додана перевірка на `visible` - дуже гарно

2024-02-05 14:48 UTC, auris1g3 commented on src/test/java/lesson13/SwagLabsTest.java
> +        inventoryPage.clickOnCartBadge();
А ось тут, якщо були б параметри, про які я писав вище, то тест читався б легше. Було б зрозуміло, які самі вартості ми матчим.

2024-02-05 15:56 UTC, vlad-hedz-quarks-tech commented on src/main/java/pages/SwagLabs/CartPage.java
> +        }
виніс

2024-02-05 15:56 UTC, vlad-hedz-quarks-tech commented on src/main/java/pages/SwagLabs/CartPage.java
> +    private static final SelenideElement CHECKOUT_BUTTON = $("[data-test='checkout']");
не зрозумів, у мене ж так і написано

2024-02-05 15:56 UTC, vlad-hedz-quarks-tech commented on src/main/java/pages/SwagLabs/InventoryPage.java
> +                INVENTORY_ITEMS.get(i).$(ADD_TO_CART_BUTTON_LOCATOR).click();
виніс

2024-02-06 05:37 UTC, auris1g3 approved these changes

2024-02-06 05:37 UTC, auris1g3 commented on src/main/java/pages/SwagLabs/InventoryPage.java
> +            for (int i = 0; i < INVENTORY_ITEMS.size(); i++) {
До теми не відноситься, але для додаткового вивчання глянь ось це
https://javarush.com/ua/groups/posts/uk.2733.java-varargs

2024-02-06 05:38 UTC, auris1g3 commented on src/main/java/pages/SwagLabs/CartPage.java
> +    private static final SelenideElement CHECKOUT_BUTTON = $("[data-test='checkout']");
Так я навпаки похвалив))

2024-02-06 07:53 UTC, merged